'use strict';
const oneDriveAPI = require('onedrive-api');
const querystring = require('querystring');

const commons = require('../../microsoft-commons');
const lib = require('../lib');
const PAGE_SIZE = 10000; // Number of items to retrieve per page

module.exports = {

    // The shape of one emitted record. Shared with FindFilesOrFolders, whose out port is
    // generated by this component.
    ITEM_SCHEMA: lib.DRIVE_ITEM_SCHEMA,

    async receive(context) {

        if (context.properties.generateOutputPortOptions) {
            return context.sendJson(lib.buildDriveItemPortOptions(context.messages.in.content.outputType), 'out');
        }

        const {
            driveId,
            outputType,
            recursive,
            fileTypesRestriction
        } = context.messages.in.content;

        if (!driveId) {
            throw new context.CancelError('Drive ID is required!');
        }

        const files = recursive ? await listFolderRecursive(context) : await listFolder(context);

        if (Array.isArray(files) && files.length > 0) {
            // Normalize fileTypesRestriction to array format for multiselect field
            if (fileTypesRestriction) {
                const normalizedFileTypesRestriction = lib.normalizeMultiselectInput(fileTypesRestriction, context, 'File Types Restriction');
                if (normalizedFileTypesRestriction.length > 0) {
                    const allowedFiles = files.filter(file =>
                        normalizedFileTypesRestriction.some(typeRestriction =>
                            file.file?.mimeType.startsWith(typeRestriction)
                        )
                    );
                    if (allowedFiles.length === 0) {
                        return context.sendJson({}, 'notFound');
                    }
                    return await commons.sendArrayOutput({
                        context,
                        outputType,
                        records: allowedFiles
                    });
                }
            }

            return await commons.sendArrayOutput({
                context,
                outputType,
                records: files
            });
        } else {
            return context.sendJson({}, 'notFound');
        }
    }
};

/**
 * calling the `delta` endpoint to get all the files in the folder
 * @param context
 * @returns {Promise<*[]>}
 */
const listFolderRecursive = async (context) => {

    let {
        driveId,
        parentId,
        parentPath,
        limit = 100,
        select
    } = context.messages.in.content;

    const endpoint = commons.getDeltaLink({ driveId, parentId, parentPath });

    if (select && !select.includes('file')) {
        // we need to get the file property to know if it's a folder or not
        select += ',file';
    }
    const params = { select, '$top': PAGE_SIZE };

    let url = `${endpoint}?${querystring.stringify(params)}`;
    let hasMore = true;
    let needMore = true;
    let failsafe = 0;
    let result = [];

    while (hasMore && needMore && failsafe < limit) {

        const page = await listFolderRecursiveAction(context, url);
        result = result.concat(page.value);
        hasMore = page['@odata.nextLink'];
        needMore = result.length < limit;
        failsafe += 1;
        url = page['@odata.nextLink'];
    }

    result = result.slice(0, limit); // strip items over the limit
    return result;
};

const listFolderRecursiveAction = async (context, url) => {

    return await commons.formatError(async () => {

        const { data } = await commons.msGraphRequest(context, {
            action: url
        });

        data.value = data.value.filter(item => item.file); // files only
        return data;
    });
};

const listFolder = async (context) => {

    const {
        driveId,
        parentId,
        parentPath,
        limit,
        select,
        orderby,
        filter
    } = context.messages.in.content;

    const { accessToken, profileInfo } = context.auth;

    const MAX_LIMIT = limit || 100;
    let files = [];
    let nextLink = null;
    let totalFiles = 0;
    const queryParameters = { select, orderby, filter, top: Math.min(PAGE_SIZE, MAX_LIMIT - totalFiles) };

    const query = Object.entries(queryParameters)
        .map(([key, value]) => value && `${key}=${value}`)
        .filter(Boolean)
        .join('&');
    do {
        const options = {
            accessToken,
            itemId: parentId,
            itemPath: parentPath,
            drive: 'drive',
            driveId,
            skipToken: nextLink ? nextLink.split('?skiptoken=')[1] : null,
            query: `?${query}`
        };

        const result = await commons.formatError(async () => {
            return oneDriveAPI.items.listChildren(options);
        }, `Failed to list files in the folder "${parentId || parentPath}" from your SharePoint account (${profileInfo.userPrincipalName}).`);

        files = files.concat(result.value);
        nextLink = result['@odata.nextLink'];
        totalFiles += result.value.length;
    } while (nextLink && totalFiles < MAX_LIMIT);

    return files;
};
